export const strings = {
  title: 'BILD DEFENCE',
  subtitle: 'Страж последнего рубежа',
  start: 'Начать забег',
  settings: 'Настройки',
  pause: 'Пауза',
  resume: 'Продолжить',
  exit: 'Выйти в меню',
  leaveTitle: 'Завершить забег?',
  leaveHint: 'Текущий прогресс забега будет потерян.',
  stay: 'Остаться',
  confirmExit: 'Завершить',
  close: 'Закрыть',
  wave: 'Тестовая волна',
  preparation: 'Оборона рубежа',
  victory: 'Рубеж удержан',
  defeat: 'Страж пал',
  victoryHint: 'Все враги уничтожены.',
  defeatHint: 'Враги прорвались к стражу.',
  restart: 'Повторить забег',
  health: 'Здоровье стража',
  enemies: 'Враги',
  time: 'Время',
  music: 'Музыка',
  effects: 'Эффекты',
  vibration: 'Вибрация',
  reducedEffects: 'Сниженные эффекты',
  foundation: 'Дом стража',
} as const;
