export const strings = {
  title: 'BILD DEFENCE',
  subtitle: 'Страж последнего рубежа',
  start: 'Начать забег',
  settings: 'Настройки',
  pause: 'Пауза',
  resume: 'Продолжить',
  exit: 'Выйти в меню',
  leaveTitle: 'Завершить забег?',
  leaveHint: 'Текущий прогресс забега будет потерян.',
  stay: 'Остаться',
  confirmExit: 'Завершить',
  close: 'Закрыть',
  wave: 'Волна 0 / 0',
  preparation: 'Подготовка арены',
  music: 'Музыка',
  effects: 'Эффекты',
  vibration: 'Вибрация',
  reducedEffects: 'Сниженные эффекты',
  foundation: 'Нулевой вертикальный срез',
} as const;
